[package]
name = "neural-network"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.15.0"
futures = "0.3.30"
lazy_static = "1.4.0"
wgpu = { version = "0.19.3", features = ["wgsl"] }

[features]
simd = []
